@echo off
J:
cd /d J:\nlp\CD-C3DA\.worktrees\reproduce-best-8c7f6b4
set RUN_DIR=runs\bgca_aste_stage1_best_8c7f6b4_rebuild_from_saved_upstream_v1\rest16_to_laptop14
set HIST_RUN=J:\nlp\CD-C3DA\runs\bgca_aste_stage1_domain_prompt_text_v1\rest16_to_laptop14
set HIST_EXTRACTOR=%HIST_RUN%\models\extractor_ep25_plain_last\best
set HIST_GENERATOR=%HIST_RUN%\models\generator_label_to_text_gen_ep8\best
J:\conda\envs\c3da\python.exe t5_aste_pipeline.py prepare --source_dataset rest16 --target_dataset laptop14 --run_dir %RUN_DIR% --seed 1000 --augment_prompt_style label_to_text --augment_channel_mode all --domain_prefix_style text --generator_output_tag label_to_text_gen --no_task_prefix
if errorlevel 1 exit /b %errorlevel%
J:\conda\envs\c3da\python.exe t5_aste_pipeline.py pseudo --run_dir %RUN_DIR% --model_path %HIST_EXTRACTOR% --batch_size 2 --num_beams 1 --max_new_tokens 128 --no_constrained_decoding --cuda 0 --no_task_prefix --pseudo_model_variant last --pseudo_source_tag extractor_ep25_plain_last --high_precision_max_triplets 1 --high_precision_max_token_distance 5
if errorlevel 1 exit /b %errorlevel%
J:\conda\envs\c3da\python.exe t5_aste_pipeline.py select_complete_multi_pseudo --run_dir %RUN_DIR% --output_dir %RUN_DIR%\pseudo_variants\hp1_complete2_dist5_w025 --base_pseudo_file %RUN_DIR%\target_pseudo_high_precision.jsonl --min_pseudo_weight 0.65 --high_precision_max_token_distance 5 --complete_multi_extra_weight 0.25
if errorlevel 1 exit /b %errorlevel%
J:\conda\envs\c3da\python.exe t5_aste_pipeline.py augment --run_dir %RUN_DIR% --model_path %HIST_GENERATOR% --nli_model_path J:\nlp\models\nli-deberta-v3-base-mnli-fever-anli --augment_prompt_style masked_mutual --augment_channel_mode all --domain_prefix_style text --opinion_replacement_mode coupled_random --sentiment_vector_model_path J:\nlp\models\t5-base-py --sentiment_vector_backend t5 --glove_path J:\models\glove.6B.300d.txt --sentiment_vector_min_margin 0.05 --sentiment_vector_min_old_similarity 0.35 --sentiment_vector_no_cooccurrence_min_similarity 0.5 --augment_output_tag strict_aug150_w020_label_to_text_gen --final_train_output_tag strict_aug150_w020_label_to_text_gen --augment_select_max_rows 150 --augment_select_max_per_base 1 --augment_select_weight 0.2 --augment_select_max_opinion_ratio 1.0 --augment_select_require_raw_exact --augment_select_require_model_filter_passed --pseudo_train_source high_precision --pseudo_train_file %RUN_DIR%\target_pseudo_high_precision.jsonl --high_precision_max_triplets 1 --high_precision_max_token_distance 5 --model_filter_path %HIST_EXTRACTOR% --model_filter_mode fixed --model_filter_batch_size 2 --model_filter_num_beams 1 --model_filter_no_constrained_decoding --model_filter_channel_aware --model_filter_opinion_similarity_min 0.0 --cuda 0 --no_task_prefix
if errorlevel 1 exit /b %errorlevel%
J:\conda\envs\c3da\python.exe t5_aste_pipeline.py build_final_train_from_files --run_dir %RUN_DIR% --pseudo_train_file %RUN_DIR%\pseudo_variants\hp1_complete2_dist5_w025\target_pseudo_high_precision.jsonl --selected_augment_file %RUN_DIR%\c3da_two_channel_augmented_selected_strict_aug150_w020_label_to_text_gen.jsonl --selected_augment_weight 0.2 --final_train_output_tag strict_aug150_w020_label_to_text_gen_complete_multi2_w025_pw065 --no_task_prefix
if errorlevel 1 exit /b %errorlevel%
J:\conda\envs\c3da\python.exe t5_absa_train.py --model_path J:\nlp\models\t5-base-py --train_file %RUN_DIR%\final_train_strict_aug150_w020_label_to_text_gen_complete_multi2_w025_pw065.jsonl --dev_file %RUN_DIR%\final_dev_strict_aug150_w020_label_to_text_gen_complete_multi2_w025_pw065.jsonl --output_dir runs\bgca_aste_stage1_best_8c7f6b4_rebuild_from_saved_upstream_v1\rest16_to_laptop14\models\final_dann_l0.03_strict_aug150_w020_label_to_text_gen_complete_multi2_w025_pw065_sentiment_contrastive_l001_source_balanced_ep5 --num_train_epochs 5 --source_weight 1.0 --pseudo_weight 0.65 --augment_weight 0.2 --checkpoint_selection best --resume_from_checkpoint auto --lambda_domain_adv 0.03 --domain_adv_grl_lambda 1.0 --domain_adv_hidden_size 256 --domain_adv_exclude_augment --lambda_sentiment_contrastive 0.01 --lambda_pairing_loss 0.0 --pairing_temperature 0.1 --sentiment_contrastive_temperature 0.1 --sentiment_contrastive_min_weight 0.65 --neutral_generation_loss_gain 0.0 --neutral_generation_max_effective_weight 0.0 --sentiment_contrastive_source_only --sentiment_contrastive_class_balanced --per_device_train_batch_size 1 --per_device_eval_batch_size 2 --gradient_accumulation_steps 16 --learning_rate 0.0003 --fp16 --gradient_checkpointing --cuda 0 --seed 1000
if errorlevel 1 exit /b %errorlevel%
J:\conda\envs\c3da\python.exe t5_aste_pipeline.py evaluate --run_dir %RUN_DIR% --model_path runs\bgca_aste_stage1_best_8c7f6b4_rebuild_from_saved_upstream_v1\rest16_to_laptop14\models\final_dann_l0.03_strict_aug150_w020_label_to_text_gen_complete_multi2_w025_pw065_sentiment_contrastive_l001_source_balanced_ep5\best --batch_size 2 --num_beams 4 --max_new_tokens 96 --cuda 0 --no_task_prefix --no_constrained_decoding --output_tag strict_aug150_w020_label_to_text_gen_complete_multi2_w025_pw065_sentiment_contrastive_l001_source_balanced
